config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get '/help', 	to: 'static_pages#help'
	get '/about', 	to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'
	get '/signup', 	to: 'users#new'
	get '/login',	to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	post '/micro_posts', to: 'microposts#create'
	delete '/micro_posts', to: 'microposts#destroy'
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :users
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]
	resources :unfollow, only: [:destroy]
  	resources :follow, only: [:create]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-danger">
		The form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items,
					  params: { controller: :static_pages, action: :home } %>
<% end %> 

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	</div>
		<%= f.submit "Post", class: "btn btn-primary" %>
		<span class="image">

			<%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
		</span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
     <%= @user.following.count %>
    </strong>
    following
    </a>
    <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>