config/routes.rb
Rails.application.routes.draw do
	root 'static_pages#home'
	get '/help', 	to: 'static_pages#help'
	get '/about', 	to: 'static_pages#about'
	get '/contact', to: 'static_pages#contact'
	get '/signup', 	to: 'users#new'
	get '/login',	to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	post '/micro_posts', to: 'microposts#create'
	delete '/micro_posts', to: 'microposts#destroy'
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :users
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]
	resources :unfollow, only: [:destroy]
  	resources :follow, only: [:create]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	<nav>
		<ul>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><a href="https://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav>
        <%= link_to image_tag("favicon.ico", alt: "Rails logo" , width: "50px") ,root_path %>  
            <ul class="nav navbar-nav navbar-right  ">
                <li><%= link_to "Home" , root_path %></li>
                <li><%= link_to " Help", help_path %></li>
                    <% if logged_in? %>
                    <li><%= link_to "Users", users_path %></li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <li><%= link_to  "Profile 웃", current_user %></li>
                    <li><%= link_to "Settings ⚒ ", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                        <%= link_to "➥ Sign out ", logout_path, method: :delete %>
                    </li>
                    </ul>
                </li>
                <% else %>
                    <li><%= link_to "Sign in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head link rel="icon" href="http://www.prodraw.net/favicon/download.php?file=kopws60b_1.ico" type="imagex  -icon" >
		<title><%= full_title(yield(:title)) %></title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
			<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>